import streamlit as st
from fpdf import FPDF
import re

# --- PAGE CONFIG ---
st.set_page_config(page_title="Creator Earnings Calc", page_icon="💰", layout="centered")

# --- INDIAN CURRENCY FORMATTER ---
def format_indian_currency(number):
    """Formats a number into the Indian numbering system (Lakhs/Crores)."""
    s = str(int(number))
    if len(s) <= 3:
        return s
    last_three = s[-3:]
    remaining = s[:-3]
    # Add commas every 2 digits for the remaining part (Lakhs, Crores, etc.)
    remaining = re.sub(r'(\d+?)(?=(\d{2})+$)', r'\1,', remaining)
    return f"{remaining},{last_three}"

# --- APP INTERFACE ---
st.title("🇮🇳 Creator Earnings Calculator")
st.markdown("Professional revenue estimation for Indian content creators.")

# 1. Creator Details Section
st.subheader("Profile Information")
c1, c2 = st.columns(2)
with c1:
    creator_name = st.text_input("Full Name", placeholder="e.g. Jeeka Krishna")
with c2:
    creator_user = st.text_input("Platform Username", placeholder="e.g. @jk_analytics")

# 2. Earnings Inputs
st.divider()
col1, col2 = st.columns(2)
with col1:
    subscribers = st.number_input("Total Subscribers", min_value=0, value=100, step=10)
    sub_charge = st.number_input("Monthly Charge (₹)", min_value=0, value=290, step=10)
with col2:
    platform_fee = st.slider("Platform Commission (%)", 0, 50, 20)

# --- CALCULATIONS ---
gross_monthly = subscribers * sub_charge
net_monthly = gross_monthly * (1 - (platform_fee / 100))
annual_income = net_monthly * 12

# --- DISPLAY METRICS ---
st.divider()
# Big metric for Annual Income with Indian Formatting
st.metric(
    label="📊 ESTIMATED ANNUAL NET INCOME", 
    value=f"₹{format_indian_currency(annual_income)}"
)

m1, m2 = st.columns(2)
m1.metric("Gross Monthly", f"₹{format_indian_currency(gross_monthly)}")
m2.metric("Net Monthly", f"₹{format_indian_currency(net_monthly)}")

# --- PDF GENERATION FUNCTION ---
def generate_pdf_bytes(name, user, subs, charge, fee, m_net, y_net):
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Helvetica", "B", 22)
    pdf.cell(0, 20, "EARNINGS REPORT", ln=True, align="C")
    
    # Creator Info
    pdf.set_font("Helvetica", "", 12)
    pdf.ln(10)
    pdf.cell(0, 10, f"Creator Name: {name}", ln=True)
    pdf.cell(0, 10, f"Username: {user}", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(10)
    
    # Data Table
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(90, 10, "Description", border=1)
    pdf.cell(90, 10, "Amount/Value", border=1, ln=True)
    
    pdf.set_font("Helvetica", "", 12)
    data = [
        ("Total Active Subscribers", f"{subs:,}"),
        ("Subscription Price", f"Rs. {charge}"),
        ("Platform Fee Deduction", f"{fee}%"),
        ("Net Monthly Take-home", f"Rs. {format_indian_currency(m_net)}"),
    ]
    
    for label, val in data:
        pdf.cell(90, 10, label, border=1)
        pdf.cell(90, 10, val, border=1, ln=True)
    
    # Final Big Result in PDF
    pdf.ln(10)
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(0, 102, 204) # Professional Blue
    pdf.cell(0, 10, f"Estimated Annual Income: Rs. {format_indian_currency(y_net)}", ln=True)
    
    # Footer
    pdf.set_y(-30)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 10, "Generated by Creator Earnings Calc India - For estimation purposes only.", align="C")
    
    return bytes(pdf.output())

# --- DOWNLOAD LOGIC ---
st.divider()
st.subheader("Generate Report")

if st.button("Calculate and Prepare PDF"):
    if creator_name:
        with st.spinner("Generating Report..."):
            pdf_data = generate_pdf_bytes(
                creator_name, creator_user, subscribers, 
                sub_charge, platform_fee, net_monthly, annual_income
            )
            st.session_state['pdf_report'] = pdf_data
            st.success("✅ Report generated! You can now download it below.")
    else:
        st.error("Please enter a Creator Name to generate the report.")

if 'pdf_report' in st.session_state:
    st.download_button(
        label="📩 Download PDF Report",
        data=st.session_state['pdf_report'],
        file_name=f"{creator_name}_Earnings_Report.pdf",
        mime="application/pdf"
    )
